# Generated by Django 5.2 on 2025-04-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('niveau_etude', models.CharField(max_length=50)),
                ('etablissement_origine', models.CharField(max_length=200)),
                ('concours_souhaite', models.CharField(choices=[('L1', 'Licence 1'), ('M1', 'Master 1')], max_length=2)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('extrait_naissance', models.FileField(upload_to='extraits/')),
                ('certificat', models.FileField(upload_to='certificats/')),
                ('lettre_motivation', models.FileField(upload_to='lettres/')),
                ('diplome', models.FileField(upload_to='diplomes/')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
